Models/ErrorViewModel.cs
using System;

namespace WellaMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UserData.cs
using System.ComponentModel.DataAnnotations;

namespace WellaMvc.Models
{
    public class UserData
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string Location { get; set; }
        [Required]
        public string PhoneNumber { get; set; } 
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace WellaMvc.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/CalculateController.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace WellaMvc.Controllers
{
    public class CalculateController : Controller
    {
        //CRUD Operations - Create, Read, Update, Delete
        [HttpGet]
        public IActionResult SimpleInterest()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SimpleInterest(string amount, string months)
        {
            if (String.IsNullOrEmpty(amount) || String.IsNullOrEmpty(months)) 
            {
                ViewBag.ErrorMessage = "Amount or months must not be null";
                return View();
            }

            var amountInt = int.Parse(amount);
            var monthsInt = int.Parse(months);

            var interest = (amountInt * 2.4 * monthsInt)/100;
            
            ViewBag.Amount = amount;
            ViewBag.Months = months;
            ViewBag.Interest = interest;
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WellaMvc.Models;

namespace WellaMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WellaMvc.DatabaseContext;
using WellaMvc.Models;

namespace WellaMvc.Controllers
{
    public class UserController : Controller
    {
        private readonly AppDbContext _context;
        public UserController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var user = _context.UserDataTable.ToList();
            return View(user);
        }

        public IActionResult AddUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUser(UserData user)
        {
            if (ModelState.IsValid)
            {
                await _context.UserDataTable.AddAsync(user);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> DetailsAsync(int ID)
        {   
            var user = await _context.UserDataTable.FirstOrDefaultAsync(x => x.ID == ID);

            return View(user);
        }

        public async Task<IActionResult> EditAsync(int ID)
        {   
            var user = await _context.UserDataTable.FirstOrDefaultAsync(x => x.ID == ID);

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAsync(UserData model)
        {   
            var user = await _context.UserDataTable.FirstOrDefaultAsync(x => x.ID == model.ID);

            if (!string.IsNullOrEmpty(model.FirstName)) user.FirstName = model.FirstName; 
            if (!string.IsNullOrEmpty(model.LastName)) user.LastName = model.LastName;
            if (!string.IsNullOrEmpty(model.Email)) user.Email = model.Email;
            if (!string.IsNullOrEmpty(model.PhoneNumber)) user.PhoneNumber = model.PhoneNumber;
            if (!string.IsNullOrEmpty(model.Location)) user.Location = model.Location;

            _context.UserDataTable.Update(user);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int ID){
            {   
                var user = await _context.UserDataTable.FirstOrDefaultAsync(x => x.ID == ID);

                return View(user);
            }

            var userFromDb = _context.UserDataTable.FindAsync(ID);
        
            return View(userFromDb);
        }

        // DELETE USER
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(int ID){
            var item = _context.UserDataTable.Find(ID);
            // var item = _context.UserDataTable.FirstOrDefaultAsync(x => x.ID == ID);
            if( item == null ){
                return View(item);
               
            }
            _context.UserDataTable.Remove(item);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
           
        }
    }
}

Views/About/Index.cshtml
@{
    ViewData["Title"] = "About me";
}

<div class="text-center">
    <h1 class="display-4">About me</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Language</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Damola</td>
                <td>Olutoke</td>
            </tr>
        </tbody>
    </table>
</div>

Views/Calculate/SimpleInterest.cshtml
@{
    ViewData["Title"] = "Simple Interest";
}

<div class="text-center">
    <h1 class="display-4">Calculate the interest of any amount</h1>
    
    <div class="row">
        <div class="col-5">
            <form asp-controller="Calculate" asp-action="SimpleInterest" method="POST">
                <input type="text" name="amount" class="form-control" placeholder="Amount">
                <input type="text" name="months" class="form-control mt-3" placeholder="Months">
                <button type="submit" class="btn btn-primary mt-3">Calculate Simple Interest</button>
            </form>

            @if(ViewBag.Amount != null)
            {
                <p>Amount: @ViewBag.Amount</p>
            }
            @if(ViewBag.Months != null)
            {
                <p>Months: @ViewBag.Months</p>
            }
            @if(ViewBag.Interest != null)
            {
                <p>Interest: @ViewBag.Interest</p>
            }
            @if(ViewBag.ErrorMessage != null)
            {
                <p class="text-danger">Error: @ViewBag.ErrorMessage</p>
            }
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WellaMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WellaMvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="About" asp-action="Index">About Me</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Calculate" asp-action="SimpleInterest">Simple Interest</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WellaMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/User/AddUser.cshtml
@model UserData

@{
    ViewData["Title"] = "User Profiles";
}

<h2>Add User</h2>

<div class="row">
    <div class="col-5">
        <form asp-controller="User" asp-action="AddUser" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="text" asp-for="FirstName" class="form-control mt-2" placeholder="First name" required/>
            <input type="text" asp-for="LastName" class="form-control mt-2" placeholder="Last name" required/>
            <input type="text" asp-for="Location" class="form-control mt-2" placeholder="Location" required/>
            <input type="tel" asp-for="PhoneNumber"  class="form-control mt-2" placeholder="Phone number" required/>
            <input type="email" asp-for="Email" class="form-control mt-2" placeholder="Email"/>
            <button type="submit" class="btn btn-primary w-100 mt-2">Add</button>
        </form>
    </div>
</div>

Views/User/Delete.cshtml
@model UserData

@{
    ViewData["Title"] = "Delete User Profiles";
}

<h2>Delete User</h2>

<div class="row">
    <div class="col-5">
        <form asp-controller="User" asp-action="Delete" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="text" asp-for="FirstName" class="form-control mt-2" placeholder="First name" required disabled/>
            <input type="text" asp-for="LastName" class="form-control mt-2" placeholder="Last name" required disabled/>
            <input type="text" asp-for="Location" class="form-control mt-2" placeholder="Location" required disabled/>
            <input type="tel" asp-for="PhoneNumber"  class="form-control mt-2" placeholder="Phone number" required disabled/>
            <input type="email" asp-for="Email" class="form-control mt-2" placeholder="Email" required disabled/>
            <button type="submit" class="btn btn-danger w-100 mt-2">Delete</button>
        </form>
    </div>
</div>

Views/User/Details.cshtml
@model UserData

@{
    ViewData["Title"] = "User Profiles";
}

<h2>All Users</h2>
<a asp-controller="User" asp-action="AddUser" class="btn btn-primary">Add User</a>
<div class="text-center">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Phone Number</th>
                <th>Location</th>
                <th>Email</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                    <tr>
                        <td>@Model.FirstName @Model.LastName</td>
                        <td>@Model.PhoneNumber</td>
                        <td>@Model.Location</td>
                        <td>@Model.Email</td>
                        <td>
                            <a asp-controller="User" asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-info">
                                Edit
                            </a>
                        </td>
                        <td>
                            <a asp-controller="User" asp-action="Delete" asp-route-id="@Model.ID" class="btn btn-danger">
                                Delete
                            </a>
                        </td>
                    </tr>
            }
        </tbody>
    </table>
</div>

Views/User/Edit.cshtml
@model UserData

@{
    ViewData["Title"] = "Edit User Profiles";
}

<h2>Edit User</h2>

<div class="row">
    <div class="col-5">
        <form asp-controller="User" asp-action="Edit" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="text" asp-for="FirstName" class="form-control mt-2" placeholder="First name" required/>
            <input type="text" asp-for="LastName" class="form-control mt-2" placeholder="Last name" required/>
            <input type="text" asp-for="Location" class="form-control mt-2" placeholder="Location" required/>
            <input type="tel" asp-for="PhoneNumber"  class="form-control mt-2" placeholder="Phone number" required/>
            <input type="email" asp-for="Email" class="form-control mt-2" placeholder="Email" required/>
            <button type="submit" class="btn btn-primary w-100 mt-2">Submit</button>
        </form>
    </div>
</div>

Views/User/Index.cshtml
@model List<UserData>

@{
    ViewData["Title"] = "User Profiles";
}

<h2>All Users</h2>
<a asp-controller="User" asp-action="AddUser" class="btn btn-primary">Add User</a>
<div class="text-center">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th colspan="3">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.FirstName @item.LastName</td>
                        <td>
                            <a asp-controller="User" asp-action="Details" asp-route-id="@item.ID" class="btn btn-primary">
                                See Details
                            </a>
                        </td>
                        <td>
                            <a asp-controller="User" asp-action="Edit" asp-route-id="@item.ID" class="btn btn-info">
                                Edit
                            </a>
                        </td>
                        <td>
                            <a asp-controller="User" asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">
                                Delete
                            </a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>